workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Pipenv
          command: |
            pip install --user pipenv
      - run:
          name: Install dependencies
          command: |
            pipenv install --dev
      - save_cache:
          key: v1-dependencies-{{ checksum "Pipfile" }}
          paths:
            - ./venv
      - run:
          name: Build mkdocs site
          command: |
              pipenv run build
      - persist_to_workspace:
          root: site
          paths:
            - "**/*"

  publish:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: site
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Pipenv
          command: |
            pip install --user pipenv
      - run:
          name: Install dependencies
          command: |
            pipenv install --dev
      - save_cache:
          key: v1-dependencies-{{ checksum "Pipfile" }}
          paths:
            - ./venv
      - run:
          name: Git configuration for CI deployment
          command: |
            git config user.email $(git log --format="%aE" HEAD | head -1)
            git config user.name ${CIRCLE_USERNAME}
      - add_ssh_keys:
          fingerprints:
              - "9a:81:2e:64:05:5d:73:bb:f4:1f:7c:b7:9e:69:25:04"
      - run:
          name: Publish into GitHub pages
          command: |
              pipenv run deploy:gh-pages
