version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Pipenv
          command: |
            pip install --user pipenv
      - run:
          name: Install dependencies
          command: |
            pipenv install --dev

      - save_cache:
          key: v1-dependencies-{{ checksum "Pipfile" }}
          paths:
            - ./venv

      - run:
          name: Build mkdocs site
          command: |
              pipenv run build

#      - store_artifacts:
#          path: public/site
#          prefix: site

      # - add_ssh_keys:
      #     fingerprints:
      #       - "a9:89:22:16:a5:f1:53:6d:ef:d7:47:f8:64:8a:57:88"

      # - run:
      #     name: Deploy site to gh-pages
      #     command: |
      #       bash -c tools/ci/deploy_gh_pages.sh

    # branches:
    #     only:
    #       - master

# workflows:
#   version: 2
#   
#   build_deploy:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: master
