site_name: ambient notes
pages:
  - Home: index.md
  - About: about.md
  - Help: help.md
  - License: license.md
  - Programming:
      - PaymentRequest API: programming/paymentrequest-api.md
  - Design:
      - Jobs to be done: design/jobs-to-be-done.md
theme:
  name: "material"
  favicon: "static/image/ambient-favicon.ico"
  logo:
    icon: "create"
  palette:
     primary: "light blue"
     accent: "indigo"
  font:
     text: "Noto Sans JP"
     code: "Ubuntu Mono"
markdown_extensions:
  - codehilite(linenums=true)
  - toc:
      # this indent should be 4!!!
      permalink: "#"
      separator: "_"
  - mdx_math
  - fontawesome_markdown
  - pymdownx.emoji
  - admonition
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://fonts.googleapis.com/css?family=Ubuntu+Mono:600,800"
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"
extra:
  search:
    languages: 'en, jp'
